name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the issues with code of Hydro
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: >
        #### Thank you for reporting the issue! Please make sure what you are reporting is a bug with reproducible steps.
  - type: textarea
    attributes:
      label: 🐛 Describe the bug
      description: |
        Please provide a clear and concise description of what the bug is.
      placeholder: |
        A clear and concise description of what the bug is.

        ```python
        # Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to
        reproduce the issue.
        ```

        ```
        The error message you got, with the full traceback.
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Versions / Dependencies
      description: |
        Please specify the versions of Hydro, Ray, Pytorch, Python, OS, and other libraries that are used.
      placeholder: >
        Please specify the versions of dependencies.
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        Thanks for contributing 🎉!
